name: Merge and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run merge script
        run: npm run merge

      - name: Zip merged directory
        run: zip -r merged.zip merged

      - name: Create tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag release-${GITHUB_SHA::7}
          git push origin release-${GITHUB_SHA::7}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: merged.zip
          tag_name: release-${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

